### PR TITLE
Update haiku.md

### PR DESCRIPTION
**Pull request by Fabiwell**
lmao xdxxdxdd forntite sus among us

### CODE REVIEW

**Comment by Fabiwell** [comment]
🥵 🥵 🍆 🍑 💦 💦 🥵 🥵 🦢

**Comment by 87606** [comment]
💯 🔥

**Comment by Fabiwell** [comment]
👩 🔫 💦 🍆 🥵

**Comment by 87606** [comment]
Ayo fabiwell Very good job

**Comment by Fabiwell** [comment]
[😉 ](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Pull request merged**
